version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: auth_server
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm run dev
  db:
    image: 'redis'
    container_name: auth_db
    ports:
      - '127.0.0.1:6379:6379'
